#ifndef QCTIMINGMASTER_H
#define QCTIMINGMASTER_H

#define QCTM_CAMERA_TICKRATE 1000
#define QCTM_CAMERA_BAD_FRAME_COUNT_FOR_RECONNECT 10
#define QCTM_CAMERA_ERROR_SLEEP 3000

#define QCTM_KL46_WAITFORREADYREAD 250
#define QCTM_KL46_QUERYTICKRATE 250
#define QCTM_KL46_WRITING_PRESLEEP 50
#define QCTM_KL46_WRITING_POSTSLEEP 50


#endif // QCTIMINGMASTER_H
